// Extension-UI strings the promo demo renders, per locale — generated from
// _locales/<loc>/messages.json. Demo mode feeds these to t() so the sidebar
// chrome (header, onboarding labels) localizes in screenshots, independent of
// Chrome's extension-UI language (which --lang does not change). Regenerate
// after editing _locales. Not used outside demo mode.

export type DemoUiStrings = Record<string, string>;

export const DEMO_UI_BY_LANG: Record<string, DemoUiStrings> = {
    am: {
        ytSidebarTitle: "ግርጌ ጽሑፍ",
        ytOnboardingTitle: "ቋንቋዎችዎን ይምረጡ",
        ytOnboardingText: "ለመጀመር የሚማሩትን ቋንቋ እና የአፍ መፍቻ ቋንቋዎን ይምረጡ።",
        ytLearningLabel: "እየተማርኩ ነው",
        ytNativeLabel: "የአፍ መፍቻ ቋንቋዬ",
        ytSelectPlaceholder: "ይምረጡ…",
        ytSearchingTitle: "የትርጉም ጽሑፎችን በመፈለግ ላይ…",
        ytSearchingText: "ለዚህ ቪዲዮ የትርጉም ጽሑፎችን በመፈለግ ላይ።",
        ytNoSubsTitle: "ምንም የትርጉም ጽሑፍ የለም",
        ytNoSubsText: "ይህ ቪዲዮ የትርጉም ጽሑፍ የለውም። ሌላ ቪዲዮ ይሞክሩ — በYouTube ላይ ያሉ ሁሉም ቪዲዮዎች የትርጉም ጽሑፍ የላቸውም።",
        ytSearchAgain: "እንደገና ፈልግ",
        ytSignInToSave: "ቃላትን ለማስቀመጥ ይግቡ",
        ytSavedBadge: "ተቀምጧል",
        ytWordsSaved: "{count} ቃላት ተቀምጠዋል",
    },
    ar: {
        ytSidebarTitle: "الترجمة",
        ytOnboardingTitle: "اختر لغاتك",
        ytOnboardingText: "اختر اللغة التي تتعلمها ولغتك الأم للبدء.",
        ytLearningLabel: "أنا أتعلم",
        ytNativeLabel: "لغتي الأم",
        ytSelectPlaceholder: "اختر…",
        ytSearchingTitle: "جارٍ البحث عن الترجمة…",
        ytSearchingText: "جارٍ البحث عن ترجمة لهذا الفيديو.",
        ytNoSubsTitle: "لا تتوفر ترجمة",
        ytNoSubsText: "لا يحتوي هذا الفيديو على ترجمة. جرّب فيديو آخر — ليست كل مقاطع الفيديو على YouTube تحتوي على ترجمة.",
        ytSearchAgain: "ابحث مرة أخرى",
        ytSignInToSave: "سجّل الدخول لحفظ الكلمات",
        ytSavedBadge: "تم الحفظ",
        ytWordsSaved: "تم حفظ {count} كلمة",
    },
    bg: {
        ytSidebarTitle: "Субтитри",
        ytOnboardingTitle: "Изберете езици",
        ytOnboardingText: "Изберете езика, който учите, и родния си език, за да започнете.",
        ytLearningLabel: "Уча",
        ytNativeLabel: "Моят роден език",
        ytSelectPlaceholder: "Изберете…",
        ytSearchingTitle: "Търсене на субтитри…",
        ytSearchingText: "Търсене на субтитри за това видео.",
        ytNoSubsTitle: "Няма налични субтитри",
        ytNoSubsText: "Това видео няма субтитри. Опитайте друго видео — не всяко видео в YouTube има субтитри.",
        ytSearchAgain: "Търсене отново",
        ytSignInToSave: "Влезте, за да запазвате думи",
        ytSavedBadge: "запазено",
        ytWordsSaved: "Запазени думи: {count}",
    },
    bn: {
        ytSidebarTitle: "সাবটাইটেল",
        ytOnboardingTitle: "আপনার ভাষা নির্বাচন করুন",
        ytOnboardingText: "শুরু করতে আপনি যে ভাষা শিখছেন এবং আপনার মাতৃভাষা নির্বাচন করুন।",
        ytLearningLabel: "আমি শিখছি",
        ytNativeLabel: "আমার মাতৃভাষা",
        ytSelectPlaceholder: "নির্বাচন করুন…",
        ytSearchingTitle: "সাবটাইটেল খোঁজা হচ্ছে…",
        ytSearchingText: "এই ভিডিওর জন্য সাবটাইটেল খোঁজা হচ্ছে।",
        ytNoSubsTitle: "কোনো সাবটাইটেল উপলব্ধ নেই",
        ytNoSubsText: "এই ভিডিওতে কোনো সাবটাইটেল নেই। অন্য একটি ভিডিও চেষ্টা করুন — YouTube-এর সব ভিডিওতে সাবটাইটেল থাকে না।",
        ytSearchAgain: "আবার খুঁজুন",
        ytSignInToSave: "শব্দ সংরক্ষণ করতে সাইন ইন করুন",
        ytSavedBadge: "সংরক্ষিত",
        ytWordsSaved: "{count} শব্দ সংরক্ষিত",
    },
    ca: {
        ytSidebarTitle: "Subtítols",
        ytOnboardingTitle: "Trieu els vostres idiomes",
        ytOnboardingText: "Trieu l'idioma que esteu aprenent i la vostra llengua materna per començar.",
        ytLearningLabel: "Estic aprenent",
        ytNativeLabel: "La meva llengua materna",
        ytSelectPlaceholder: "Seleccioneu…",
        ytSearchingTitle: "S'estan cercant subtítols…",
        ytSearchingText: "S'estan cercant subtítols per a aquest vídeo.",
        ytNoSubsTitle: "No hi ha subtítols disponibles",
        ytNoSubsText: "Aquest vídeo no té subtítols. Proveu un altre vídeo: no tots els vídeos de YouTube tenen subtítols.",
        ytSearchAgain: "Torna a cercar",
        ytSignInToSave: "Inicia la sessió per desar paraules",
        ytSavedBadge: "desat",
        ytWordsSaved: "{count} paraules desades",
    },
    cs: {
        ytSidebarTitle: "Titulky",
        ytOnboardingTitle: "Vyberte jazyky",
        ytOnboardingText: "Vyberte jazyk, který se učíte, a svůj rodný jazyk, abyste mohli začít.",
        ytLearningLabel: "Učím se",
        ytNativeLabel: "Můj rodný jazyk",
        ytSelectPlaceholder: "Vybrat…",
        ytSearchingTitle: "Hledání titulků…",
        ytSearchingText: "Hledání titulků k tomuto videu.",
        ytNoSubsTitle: "Žádné titulky nejsou k dispozici",
        ytNoSubsText: "Toto video nemá titulky. Zkuste jiné video — ne každé video na YouTube má titulky.",
        ytSearchAgain: "Hledat znovu",
        ytSignInToSave: "Přihlaste se pro ukládání slov",
        ytSavedBadge: "uloženo",
        ytWordsSaved: "Uloženo slov: {count}",
    },
    da: {
        ytSidebarTitle: "Undertekster",
        ytOnboardingTitle: "Vælg dine sprog",
        ytOnboardingText: "Vælg det sprog, du lærer, og dit modersmål for at begynde.",
        ytLearningLabel: "Jeg lærer",
        ytNativeLabel: "Mit modersmål",
        ytSelectPlaceholder: "Vælg…",
        ytSearchingTitle: "Søger efter undertekster…",
        ytSearchingText: "Søger efter undertekster til denne video.",
        ytNoSubsTitle: "Ingen undertekster tilgængelige",
        ytNoSubsText: "Denne video har ingen undertekster. Prøv en anden video — ikke alle videoer på YouTube har undertekster.",
        ytSearchAgain: "Søg igen",
        ytSignInToSave: "Log ind for at gemme ord",
        ytSavedBadge: "gemt",
        ytWordsSaved: "{count} ord gemt",
    },
    de: {
        ytSidebarTitle: "Untertitel",
        ytOnboardingTitle: "Sprachen auswählen",
        ytOnboardingText: "Wähle die Sprache, die du lernst, und deine Muttersprache, um zu starten.",
        ytLearningLabel: "Ich lerne",
        ytNativeLabel: "Meine Muttersprache",
        ytSelectPlaceholder: "Auswählen…",
        ytSearchingTitle: "Untertitel werden gesucht…",
        ytSearchingText: "Untertitel für dieses Video werden gesucht.",
        ytNoSubsTitle: "Keine Untertitel verfügbar",
        ytNoSubsText: "Dieses Video hat keine Untertitel. Versuche ein anderes Video – nicht jedes Video auf YouTube hat Untertitel.",
        ytSearchAgain: "Erneut suchen",
        ytSignInToSave: "Anmelden, um Wörter zu speichern",
        ytSavedBadge: "gespeichert",
        ytWordsSaved: "{count} Wörter gespeichert",
    },
    el: {
        ytSidebarTitle: "Υπότιτλοι",
        ytOnboardingTitle: "Επιλέξτε τις γλώσσες σας",
        ytOnboardingText: "Επιλέξτε τη γλώσσα που μαθαίνετε και τη μητρική σας γλώσσα για να ξεκινήσετε.",
        ytLearningLabel: "Μαθαίνω",
        ytNativeLabel: "Η μητρική μου γλώσσα",
        ytSelectPlaceholder: "Επιλέξτε…",
        ytSearchingTitle: "Αναζήτηση υποτίτλων…",
        ytSearchingText: "Αναζήτηση υποτίτλων για αυτό το βίντεο.",
        ytNoSubsTitle: "Δεν υπάρχουν διαθέσιμοι υπότιτλοι",
        ytNoSubsText: "Αυτό το βίντεο δεν έχει υπότιτλους. Δοκιμάστε άλλο βίντεο — δεν έχουν όλα τα βίντεο στο YouTube υπότιτλους.",
        ytSearchAgain: "Αναζήτηση ξανά",
        ytSignInToSave: "Συνδεθείτε για αποθήκευση λέξεων",
        ytSavedBadge: "αποθηκεύτηκε",
        ytWordsSaved: "{count} λέξεις αποθηκεύτηκαν",
    },
    en: {
        ytSidebarTitle: "Subtitles",
        ytOnboardingTitle: "Choose your languages",
        ytOnboardingText: "Pick the language you're learning and your native language to start.",
        ytLearningLabel: "I'm learning",
        ytNativeLabel: "My native language",
        ytSelectPlaceholder: "Select…",
        ytSearchingTitle: "Searching for subtitles…",
        ytSearchingText: "Looking for captions for this video.",
        ytNoSubsTitle: "No subtitles available",
        ytNoSubsText: "This video doesn't have subtitles. Try another video — not every video on YouTube has captions.",
        ytSearchAgain: "Search again",
        ytSignInToSave: "Sign in to save words",
        ytSavedBadge: "saved",
        ytWordsSaved: "{count} words saved",
    },
    "en_GB": {
        ytSidebarTitle: "Subtitles",
        ytOnboardingTitle: "Choose your languages",
        ytOnboardingText: "Pick the language you're learning and your native language to start.",
        ytLearningLabel: "I'm learning",
        ytNativeLabel: "My native language",
        ytSelectPlaceholder: "Select…",
        ytSearchingTitle: "Searching for subtitles…",
        ytSearchingText: "Looking for captions for this video.",
        ytNoSubsTitle: "No subtitles available",
        ytNoSubsText: "This video doesn't have subtitles. Try another video — not every video on YouTube has captions.",
        ytSearchAgain: "Search again",
        ytSignInToSave: "Sign in to save words",
        ytSavedBadge: "saved",
        ytWordsSaved: "{count} words saved",
    },
    "en_US": {
        ytSidebarTitle: "Subtitles",
        ytOnboardingTitle: "Choose your languages",
        ytOnboardingText: "Pick the language you're learning and your native language to start.",
        ytLearningLabel: "I'm learning",
        ytNativeLabel: "My native language",
        ytSelectPlaceholder: "Select…",
        ytSearchingTitle: "Searching for subtitles…",
        ytSearchingText: "Looking for captions for this video.",
        ytNoSubsTitle: "No subtitles available",
        ytNoSubsText: "This video doesn't have subtitles. Try another video — not every video on YouTube has captions.",
        ytSearchAgain: "Search again",
        ytSignInToSave: "Sign in to save words",
        ytSavedBadge: "saved",
        ytWordsSaved: "{count} words saved",
    },
    es: {
        ytSidebarTitle: "Subtítulos",
        ytOnboardingTitle: "Elige tus idiomas",
        ytOnboardingText: "Elige el idioma que estás aprendiendo y tu idioma nativo para empezar.",
        ytLearningLabel: "Estoy aprendiendo",
        ytNativeLabel: "Mi idioma nativo",
        ytSelectPlaceholder: "Seleccionar…",
        ytSearchingTitle: "Buscando subtítulos…",
        ytSearchingText: "Buscando subtítulos para este vídeo.",
        ytNoSubsTitle: "No hay subtítulos disponibles",
        ytNoSubsText: "Este vídeo no tiene subtítulos. Prueba con otro vídeo: no todos los vídeos de YouTube tienen subtítulos.",
        ytSearchAgain: "Buscar de nuevo",
        ytSignInToSave: "Inicia sesión para guardar palabras",
        ytSavedBadge: "guardado",
        ytWordsSaved: "{count} palabras guardadas",
    },
    "es_419": {
        ytSidebarTitle: "Subtítulos",
        ytOnboardingTitle: "Elige tus idiomas",
        ytOnboardingText: "Elige el idioma que estás aprendiendo y tu idioma nativo para empezar.",
        ytLearningLabel: "Estoy aprendiendo",
        ytNativeLabel: "Mi idioma nativo",
        ytSelectPlaceholder: "Seleccionar…",
        ytSearchingTitle: "Buscando subtítulos…",
        ytSearchingText: "Buscando subtítulos para este video.",
        ytNoSubsTitle: "No hay subtítulos disponibles",
        ytNoSubsText: "Este video no tiene subtítulos. Prueba con otro video: no todos los videos de YouTube tienen subtítulos.",
        ytSearchAgain: "Buscar de nuevo",
        ytSignInToSave: "Inicia sesión para guardar palabras",
        ytSavedBadge: "guardado",
        ytWordsSaved: "{count} palabras guardadas",
    },
    et: {
        ytSidebarTitle: "Subtiitrid",
        ytOnboardingTitle: "Valige oma keeled",
        ytOnboardingText: "Alustamiseks valige õpitav keel ja oma emakeel.",
        ytLearningLabel: "Õpin",
        ytNativeLabel: "Minu emakeel",
        ytSelectPlaceholder: "Valige…",
        ytSearchingTitle: "Subtiitrite otsimine…",
        ytSearchingText: "Selle video subtiitrite otsimine.",
        ytNoSubsTitle: "Subtiitreid pole saadaval",
        ytNoSubsText: "Sellel videol pole subtiitreid. Proovige teist videot — kõigil YouTube'i videotel pole subtiitreid.",
        ytSearchAgain: "Otsi uuesti",
        ytSignInToSave: "Logi sisse sõnade salvestamiseks",
        ytSavedBadge: "salvestatud",
        ytWordsSaved: "{count} sõna salvestatud",
    },
    fa: {
        ytSidebarTitle: "زیرنویس",
        ytOnboardingTitle: "زبان‌های خود را انتخاب کنید",
        ytOnboardingText: "برای شروع، زبانی که در حال یادگیری آن هستید و زبان مادری خود را انتخاب کنید.",
        ytLearningLabel: "در حال یادگیری",
        ytNativeLabel: "زبان مادری من",
        ytSelectPlaceholder: "انتخاب کنید…",
        ytSearchingTitle: "در حال جستجوی زیرنویس…",
        ytSearchingText: "در حال جستجوی زیرنویس برای این ویدیو.",
        ytNoSubsTitle: "زیرنویسی موجود نیست",
        ytNoSubsText: "این ویدیو زیرنویس ندارد. ویدیوی دیگری را امتحان کنید — همه ویدیوهای YouTube زیرنویس ندارند.",
        ytSearchAgain: "جستجوی دوباره",
        ytSignInToSave: "برای ذخیره کلمات وارد شوید",
        ytSavedBadge: "ذخیره شد",
        ytWordsSaved: "{count} کلمه ذخیره شد",
    },
    fi: {
        ytSidebarTitle: "Tekstitykset",
        ytOnboardingTitle: "Valitse kielesi",
        ytOnboardingText: "Valitse opiskelemasi kieli ja äidinkielesi aloittaaksesi.",
        ytLearningLabel: "Opiskelen",
        ytNativeLabel: "Äidinkieleni",
        ytSelectPlaceholder: "Valitse…",
        ytSearchingTitle: "Etsitään tekstityksiä…",
        ytSearchingText: "Etsitään tekstityksiä tälle videolle.",
        ytNoSubsTitle: "Ei tekstityksiä saatavilla",
        ytNoSubsText: "Tällä videolla ei ole tekstityksiä. Kokeile toista videota — kaikissa YouTube-videoissa ei ole tekstityksiä.",
        ytSearchAgain: "Hae uudelleen",
        ytSignInToSave: "Kirjaudu sisään tallentaaksesi sanoja",
        ytSavedBadge: "tallennettu",
        ytWordsSaved: "{count} sanaa tallennettu",
    },
    fil: {
        ytSidebarTitle: "Mga Subtitle",
        ytOnboardingTitle: "Piliin ang iyong mga wika",
        ytOnboardingText: "Piliin ang wikang pinag-aaralan mo at ang iyong katutubong wika para magsimula.",
        ytLearningLabel: "Nag-aaral ako ng",
        ytNativeLabel: "Aking katutubong wika",
        ytSelectPlaceholder: "Pumili…",
        ytSearchingTitle: "Naghahanap ng mga subtitle…",
        ytSearchingText: "Naghahanap ng mga subtitle para sa video na ito.",
        ytNoSubsTitle: "Walang available na subtitle",
        ytNoSubsText: "Walang subtitle ang video na ito. Subukan ang ibang video — hindi lahat ng video sa YouTube ay may subtitle.",
        ytSearchAgain: "Maghanap muli",
        ytSignInToSave: "Mag-sign in para i-save ang mga salita",
        ytSavedBadge: "naka-save",
        ytWordsSaved: "{count} salita ang naka-save",
    },
    fr: {
        ytSidebarTitle: "Sous-titres",
        ytOnboardingTitle: "Choisissez vos langues",
        ytOnboardingText: "Choisissez la langue que vous apprenez et votre langue maternelle pour commencer.",
        ytLearningLabel: "J'apprends",
        ytNativeLabel: "Ma langue maternelle",
        ytSelectPlaceholder: "Sélectionner…",
        ytSearchingTitle: "Recherche de sous-titres…",
        ytSearchingText: "Recherche des sous-titres pour cette vidéo.",
        ytNoSubsTitle: "Aucun sous-titre disponible",
        ytNoSubsText: "Cette vidéo n'a pas de sous-titres. Essayez une autre vidéo — toutes les vidéos YouTube n'ont pas de sous-titres.",
        ytSearchAgain: "Rechercher à nouveau",
        ytSignInToSave: "Connectez-vous pour enregistrer des mots",
        ytSavedBadge: "enregistré",
        ytWordsSaved: "{count} mots enregistrés",
    },
    gu: {
        ytSidebarTitle: "સબટાઈટલ",
        ytOnboardingTitle: "તમારી ભાષાઓ પસંદ કરો",
        ytOnboardingText: "શરૂ કરવા માટે તમે જે ભાષા શીખી રહ્યા છો તે અને તમારી માતૃભાષા પસંદ કરો.",
        ytLearningLabel: "હું શીખી રહ્યો છું",
        ytNativeLabel: "મારી માતૃભાષા",
        ytSelectPlaceholder: "પસંદ કરો…",
        ytSearchingTitle: "સબટાઈટલ શોધી રહ્યાં છીએ…",
        ytSearchingText: "આ વિડિઓ માટે સબટાઈટલ શોધી રહ્યાં છીએ.",
        ytNoSubsTitle: "કોઈ સબટાઈટલ ઉપલબ્ધ નથી",
        ytNoSubsText: "આ વિડિઓમાં સબટાઈટલ નથી. બીજો વિડિઓ અજમાવો — YouTube પરના દરેક વિડિઓમાં સબટાઈટલ હોતા નથી.",
        ytSearchAgain: "ફરી શોધો",
        ytSignInToSave: "શબ્દો સાચવવા સાઇન ઇન કરો",
        ytSavedBadge: "સાચવ્યું",
        ytWordsSaved: "{count} શબ્દો સાચવ્યા",
    },
    he: {
        ytSidebarTitle: "כתוביות",
        ytOnboardingTitle: "בחר את השפות שלך",
        ytOnboardingText: "בחר את השפה שאתה לומד ואת שפת האם שלך כדי להתחיל.",
        ytLearningLabel: "אני לומד",
        ytNativeLabel: "שפת האם שלי",
        ytSelectPlaceholder: "בחר…",
        ytSearchingTitle: "מחפש כתוביות…",
        ytSearchingText: "מחפש כתוביות לסרטון הזה.",
        ytNoSubsTitle: "אין כתוביות זמינות",
        ytNoSubsText: "לסרטון הזה אין כתוביות. נסה סרטון אחר — לא לכל סרטון ב-YouTube יש כתוביות.",
        ytSearchAgain: "חפש שוב",
        ytSignInToSave: "היכנסו כדי לשמור מילים",
        ytSavedBadge: "נשמר",
        ytWordsSaved: "{count} מילים נשמרו",
    },
    hi: {
        ytSidebarTitle: "उपशीर्षक",
        ytOnboardingTitle: "अपनी भाषाएँ चुनें",
        ytOnboardingText: "शुरू करने के लिए वह भाषा चुनें जो आप सीख रहे हैं और अपनी मातृभाषा चुनें।",
        ytLearningLabel: "मैं सीख रहा हूँ",
        ytNativeLabel: "मेरी मातृभाषा",
        ytSelectPlaceholder: "चुनें…",
        ytSearchingTitle: "सबटाइटल खोजे जा रहे हैं…",
        ytSearchingText: "इस वीडियो के लिए सबटाइटल खोजे जा रहे हैं।",
        ytNoSubsTitle: "कोई सबटाइटल उपलब्ध नहीं",
        ytNoSubsText: "इस वीडियो में सबटाइटल नहीं हैं। कोई दूसरा वीडियो आज़माएँ — YouTube पर हर वीडियो में सबटाइटल नहीं होते।",
        ytSearchAgain: "फिर से खोजें",
        ytSignInToSave: "शब्द सहेजने के लिए साइन इन करें",
        ytSavedBadge: "सहेजा गया",
        ytWordsSaved: "{count} शब्द सहेजे गए",
    },
    hr: {
        ytSidebarTitle: "Titlovi",
        ytOnboardingTitle: "Odaberite jezike",
        ytOnboardingText: "Odaberite jezik koji učite i svoj materinski jezik za početak.",
        ytLearningLabel: "Učim",
        ytNativeLabel: "Moj materinski jezik",
        ytSelectPlaceholder: "Odaberite…",
        ytSearchingTitle: "Traženje titlova…",
        ytSearchingText: "Traženje titlova za ovaj videozapis.",
        ytNoSubsTitle: "Nema dostupnih titlova",
        ytNoSubsText: "Ovaj videozapis nema titlove. Pokušajte s drugim videozapisom — nemaju svi videozapisi na YouTubeu titlove.",
        ytSearchAgain: "Traži ponovno",
        ytSignInToSave: "Prijavite se za spremanje riječi",
        ytSavedBadge: "spremljeno",
        ytWordsSaved: "Spremljeno riječi: {count}",
    },
    hu: {
        ytSidebarTitle: "Feliratok",
        ytOnboardingTitle: "Válassza ki a nyelveket",
        ytOnboardingText: "Válassza ki a tanult nyelvet és az anyanyelvét a kezdéshez.",
        ytLearningLabel: "Ezt tanulom",
        ytNativeLabel: "Az anyanyelvem",
        ytSelectPlaceholder: "Válasszon…",
        ytSearchingTitle: "Feliratok keresése…",
        ytSearchingText: "Feliratok keresése ehhez a videóhoz.",
        ytNoSubsTitle: "Nincs elérhető felirat",
        ytNoSubsText: "Ehhez a videóhoz nincs felirat. Próbáljon meg másik videót — nem minden YouTube-videóhoz van felirat.",
        ytSearchAgain: "Keresés újra",
        ytSignInToSave: "Jelentkezz be a szavak mentéséhez",
        ytSavedBadge: "mentve",
        ytWordsSaved: "{count} szó mentve",
    },
    id: {
        ytSidebarTitle: "Subtitel",
        ytOnboardingTitle: "Pilih bahasa Anda",
        ytOnboardingText: "Pilih bahasa yang Anda pelajari dan bahasa ibu Anda untuk memulai.",
        ytLearningLabel: "Saya belajar",
        ytNativeLabel: "Bahasa ibu saya",
        ytSelectPlaceholder: "Pilih…",
        ytSearchingTitle: "Mencari subtitle…",
        ytSearchingText: "Mencari subtitle untuk video ini.",
        ytNoSubsTitle: "Tidak ada subtitle tersedia",
        ytNoSubsText: "Video ini tidak memiliki subtitle. Coba video lain — tidak semua video di YouTube memiliki subtitle.",
        ytSearchAgain: "Cari lagi",
        ytSignInToSave: "Masuk untuk menyimpan kata",
        ytSavedBadge: "tersimpan",
        ytWordsSaved: "{count} kata tersimpan",
    },
    it: {
        ytSidebarTitle: "Sottotitoli",
        ytOnboardingTitle: "Scegli le tue lingue",
        ytOnboardingText: "Scegli la lingua che stai imparando e la tua lingua madre per iniziare.",
        ytLearningLabel: "Sto imparando",
        ytNativeLabel: "La mia lingua madre",
        ytSelectPlaceholder: "Seleziona…",
        ytSearchingTitle: "Ricerca dei sottotitoli…",
        ytSearchingText: "Ricerca dei sottotitoli per questo video.",
        ytNoSubsTitle: "Nessun sottotitolo disponibile",
        ytNoSubsText: "Questo video non ha sottotitoli. Prova un altro video: non tutti i video su YouTube hanno i sottotitoli.",
        ytSearchAgain: "Cerca di nuovo",
        ytSignInToSave: "Accedi per salvare le parole",
        ytSavedBadge: "salvato",
        ytWordsSaved: "{count} parole salvate",
    },
    ja: {
        ytSidebarTitle: "字幕",
        ytOnboardingTitle: "言語を選択",
        ytOnboardingText: "学習中の言語と母国語を選んで始めましょう。",
        ytLearningLabel: "学習中の言語",
        ytNativeLabel: "母国語",
        ytSelectPlaceholder: "選択…",
        ytSearchingTitle: "字幕を検索中…",
        ytSearchingText: "この動画の字幕を検索しています。",
        ytNoSubsTitle: "字幕がありません",
        ytNoSubsText: "この動画には字幕がありません。別の動画をお試しください。YouTube のすべての動画に字幕があるわけではありません。",
        ytSearchAgain: "再検索",
        ytSignInToSave: "ログインして単語を保存",
        ytSavedBadge: "保存済み",
        ytWordsSaved: "{count}個の単語を保存しました",
    },
    kn: {
        ytSidebarTitle: "ಉಪಶೀರ್ಷಿಕೆಗಳು",
        ytOnboardingTitle: "ನಿಮ್ಮ ಭಾಷೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        ytOnboardingText: "ಪ್ರಾರಂಭಿಸಲು ನೀವು ಕಲಿಯುತ್ತಿರುವ ಭಾಷೆ ಮತ್ತು ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
        ytLearningLabel: "ನಾನು ಕಲಿಯುತ್ತಿದ್ದೇನೆ",
        ytNativeLabel: "ನನ್ನ ಮಾತೃಭಾಷೆ",
        ytSelectPlaceholder: "ಆಯ್ಕೆಮಾಡಿ…",
        ytSearchingTitle: "ಉಪಶೀರ್ಷಿಕೆಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ…",
        ytSearchingText: "ಈ ವೀಡಿಯೊಗಾಗಿ ಉಪಶೀರ್ಷಿಕೆಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ.",
        ytNoSubsTitle: "ಯಾವುದೇ ಉಪಶೀರ್ಷಿಕೆಗಳು ಲಭ್ಯವಿಲ್ಲ",
        ytNoSubsText: "ಈ ವೀಡಿಯೊದಲ್ಲಿ ಉಪಶೀರ್ಷಿಕೆಗಳಿಲ್ಲ. ಬೇರೆ ವೀಡಿಯೊವನ್ನು ಪ್ರಯತ್ನಿಸಿ — YouTube ನಲ್ಲಿರುವ ಎಲ್ಲಾ ವೀಡಿಯೊಗಳಲ್ಲಿ ಉಪಶೀರ್ಷಿಕೆಗಳಿರುವುದಿಲ್ಲ.",
        ytSearchAgain: "ಮತ್ತೆ ಹುಡುಕಿ",
        ytSignInToSave: "ಪದಗಳನ್ನು ಉಳಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
        ytSavedBadge: "ಉಳಿಸಲಾಗಿದೆ",
        ytWordsSaved: "{count} ಪದಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ",
    },
    ko: {
        ytSidebarTitle: "자막",
        ytOnboardingTitle: "언어 선택",
        ytOnboardingText: "시작하려면 학습 중인 언어와 모국어를 선택하세요.",
        ytLearningLabel: "학습 중인 언어",
        ytNativeLabel: "모국어",
        ytSelectPlaceholder: "선택…",
        ytSearchingTitle: "자막 검색 중…",
        ytSearchingText: "이 동영상의 자막을 검색하는 중입니다.",
        ytNoSubsTitle: "사용할 수 있는 자막 없음",
        ytNoSubsText: "이 동영상에는 자막이 없습니다. 다른 동영상을 시도해 보세요. YouTube의 모든 동영상에 자막이 있는 것은 아닙니다.",
        ytSearchAgain: "다시 검색",
        ytSignInToSave: "로그인하여 단어 저장",
        ytSavedBadge: "저장됨",
        ytWordsSaved: "단어 {count}개 저장됨",
    },
    lt: {
        ytSidebarTitle: "Subtitrai",
        ytOnboardingTitle: "Pasirinkite kalbas",
        ytOnboardingText: "Norėdami pradėti, pasirinkite mokomą kalbą ir savo gimtąją kalbą.",
        ytLearningLabel: "Mokausi",
        ytNativeLabel: "Mano gimtoji kalba",
        ytSelectPlaceholder: "Pasirinkite…",
        ytSearchingTitle: "Ieškoma subtitrų…",
        ytSearchingText: "Ieškoma šio vaizdo įrašo subtitrų.",
        ytNoSubsTitle: "Subtitrų nėra",
        ytNoSubsText: "Šis vaizdo įrašas neturi subtitrų. Išbandykite kitą vaizdo įrašą — ne visi „YouTube“ vaizdo įrašai turi subtitrus.",
        ytSearchAgain: "Ieškoti dar kartą",
        ytSignInToSave: "Prisijunkite, kad išsaugotumėte žodžius",
        ytSavedBadge: "išsaugota",
        ytWordsSaved: "Išsaugota žodžių: {count}",
    },
    lv: {
        ytSidebarTitle: "Subtitri",
        ytOnboardingTitle: "Izvēlieties valodas",
        ytOnboardingText: "Lai sāktu, izvēlieties valodu, kuru mācāties, un savu dzimto valodu.",
        ytLearningLabel: "Es mācos",
        ytNativeLabel: "Mana dzimtā valoda",
        ytSelectPlaceholder: "Izvēlieties…",
        ytSearchingTitle: "Notiek subtitru meklēšana…",
        ytSearchingText: "Tiek meklēti subtitri šim videoklipam.",
        ytNoSubsTitle: "Nav pieejamu subtitru",
        ytNoSubsText: "Šim videoklipam nav subtitru. Izmēģiniet citu videoklipu — ne visiem YouTube videoklipiem ir subtitri.",
        ytSearchAgain: "Meklēt vēlreiz",
        ytSignInToSave: "Pierakstieties, lai saglabātu vārdus",
        ytSavedBadge: "saglabāts",
        ytWordsSaved: "Saglabāti {count} vārdi",
    },
    ml: {
        ytSidebarTitle: "സബ്‌ടൈറ്റിലുകൾ",
        ytOnboardingTitle: "നിങ്ങളുടെ ഭാഷകൾ തിരഞ്ഞെടുക്കുക",
        ytOnboardingText: "ആരംഭിക്കാൻ നിങ്ങൾ പഠിക്കുന്ന ഭാഷയും നിങ്ങളുടെ മാതൃഭാഷയും തിരഞ്ഞെടുക്കുക.",
        ytLearningLabel: "ഞാൻ പഠിക്കുന്നു",
        ytNativeLabel: "എന്റെ മാതൃഭാഷ",
        ytSelectPlaceholder: "തിരഞ്ഞെടുക്കുക…",
        ytSearchingTitle: "സബ്‌ടൈറ്റിലുകൾ തിരയുന്നു…",
        ytSearchingText: "ഈ വീഡിയോയ്ക്കായി സബ്‌ടൈറ്റിലുകൾ തിരയുന്നു.",
        ytNoSubsTitle: "സബ്‌ടൈറ്റിലുകൾ ലഭ്യമല്ല",
        ytNoSubsText: "ഈ വീഡിയോയിൽ സബ്‌ടൈറ്റിലുകൾ ഇല്ല. മറ്റൊരു വീഡിയോ പരീക്ഷിക്കുക — YouTube-ലെ എല്ലാ വീഡിയോകൾക്കും സബ്‌ടൈറ്റിലുകൾ ഉണ്ടാകില്ല.",
        ytSearchAgain: "വീണ്ടും തിരയുക",
        ytSignInToSave: "വാക്കുകൾ സംരക്ഷിക്കാൻ സൈൻ ഇൻ ചെയ്യുക",
        ytSavedBadge: "സംരക്ഷിച്ചു",
        ytWordsSaved: "{count} വാക്കുകൾ സംരക്ഷിച്ചു",
    },
    mr: {
        ytSidebarTitle: "उपशीर्षके",
        ytOnboardingTitle: "तुमच्या भाषा निवडा",
        ytOnboardingText: "सुरू करण्यासाठी तुम्ही शिकत असलेली भाषा आणि तुमची मातृभाषा निवडा.",
        ytLearningLabel: "मी शिकत आहे",
        ytNativeLabel: "माझी मातृभाषा",
        ytSelectPlaceholder: "निवडा…",
        ytSearchingTitle: "उपशीर्षके शोधत आहे…",
        ytSearchingText: "या व्हिडिओसाठी उपशीर्षके शोधत आहे.",
        ytNoSubsTitle: "कोणतीही उपशीर्षके उपलब्ध नाहीत",
        ytNoSubsText: "या व्हिडिओला उपशीर्षके नाहीत. दुसरा व्हिडिओ करून पहा — YouTube वरील प्रत्येक व्हिडिओला उपशीर्षके नसतात.",
        ytSearchAgain: "पुन्हा शोधा",
        ytSignInToSave: "शब्द जतन करण्यासाठी साइन इन करा",
        ytSavedBadge: "जतन केले",
        ytWordsSaved: "{count} शब्द जतन केले",
    },
    ms: {
        ytSidebarTitle: "Sari Kata",
        ytOnboardingTitle: "Pilih bahasa anda",
        ytOnboardingText: "Pilih bahasa yang anda pelajari dan bahasa ibunda anda untuk bermula.",
        ytLearningLabel: "Saya belajar",
        ytNativeLabel: "Bahasa ibunda saya",
        ytSelectPlaceholder: "Pilih…",
        ytSearchingTitle: "Mencari sari kata…",
        ytSearchingText: "Mencari sari kata untuk video ini.",
        ytNoSubsTitle: "Tiada sari kata tersedia",
        ytNoSubsText: "Video ini tiada sari kata. Cuba video lain — bukan semua video di YouTube mempunyai sari kata.",
        ytSearchAgain: "Cari semula",
        ytSignInToSave: "Log masuk untuk simpan perkataan",
        ytSavedBadge: "disimpan",
        ytWordsSaved: "{count} perkataan disimpan",
    },
    nl: {
        ytSidebarTitle: "Ondertiteling",
        ytOnboardingTitle: "Kies je talen",
        ytOnboardingText: "Kies de taal die je leert en je moedertaal om te beginnen.",
        ytLearningLabel: "Ik leer",
        ytNativeLabel: "Mijn moedertaal",
        ytSelectPlaceholder: "Selecteren…",
        ytSearchingTitle: "Ondertitels zoeken…",
        ytSearchingText: "Ondertitels voor deze video zoeken.",
        ytNoSubsTitle: "Geen ondertitels beschikbaar",
        ytNoSubsText: "Deze video heeft geen ondertitels. Probeer een andere video — niet elke video op YouTube heeft ondertitels.",
        ytSearchAgain: "Opnieuw zoeken",
        ytSignInToSave: "Log in om woorden op te slaan",
        ytSavedBadge: "opgeslagen",
        ytWordsSaved: "{count} woorden opgeslagen",
    },
    no: {
        ytSidebarTitle: "Undertekster",
        ytOnboardingTitle: "Velg språkene dine",
        ytOnboardingText: "Velg språket du lærer og morsmålet ditt for å starte.",
        ytLearningLabel: "Jeg lærer",
        ytNativeLabel: "Morsmålet mitt",
        ytSelectPlaceholder: "Velg…",
        ytSearchingTitle: "Søker etter undertekster…",
        ytSearchingText: "Søker etter undertekster for denne videoen.",
        ytNoSubsTitle: "Ingen undertekster tilgjengelig",
        ytNoSubsText: "Denne videoen har ingen undertekster. Prøv en annen video — ikke alle videoer på YouTube har undertekster.",
        ytSearchAgain: "Søk igjen",
        ytSignInToSave: "Logg inn for å lagre ord",
        ytSavedBadge: "lagret",
        ytWordsSaved: "{count} ord lagret",
    },
    pl: {
        ytSidebarTitle: "Napisy",
        ytOnboardingTitle: "Wybierz języki",
        ytOnboardingText: "Wybierz język, którego się uczysz, oraz swój język ojczysty, aby rozpocząć.",
        ytLearningLabel: "Uczę się",
        ytNativeLabel: "Mój język ojczysty",
        ytSelectPlaceholder: "Wybierz…",
        ytSearchingTitle: "Wyszukiwanie napisów…",
        ytSearchingText: "Wyszukiwanie napisów do tego filmu.",
        ytNoSubsTitle: "Brak dostępnych napisów",
        ytNoSubsText: "Ten film nie ma napisów. Spróbuj innego filmu — nie każdy film w YouTube ma napisy.",
        ytSearchAgain: "Szukaj ponownie",
        ytSignInToSave: "Zaloguj się, aby zapisać słowa",
        ytSavedBadge: "zapisano",
        ytWordsSaved: "Zapisano słów: {count}",
    },
    "pt_BR": {
        ytSidebarTitle: "Legendas",
        ytOnboardingTitle: "Escolha seus idiomas",
        ytOnboardingText: "Escolha o idioma que você está aprendendo e seu idioma nativo para começar.",
        ytLearningLabel: "Estou aprendendo",
        ytNativeLabel: "Meu idioma nativo",
        ytSelectPlaceholder: "Selecionar…",
        ytSearchingTitle: "Procurando legendas…",
        ytSearchingText: "Procurando legendas para este vídeo.",
        ytNoSubsTitle: "Nenhuma legenda disponível",
        ytNoSubsText: "Este vídeo não tem legendas. Tente outro vídeo — nem todo vídeo no YouTube tem legendas.",
        ytSearchAgain: "Procurar novamente",
        ytSignInToSave: "Faça login para salvar palavras",
        ytSavedBadge: "salvo",
        ytWordsSaved: "{count} palavras salvas",
    },
    "pt_PT": {
        ytSidebarTitle: "Legendas",
        ytOnboardingTitle: "Escolha os seus idiomas",
        ytOnboardingText: "Escolha o idioma que está a aprender e a sua língua materna para começar.",
        ytLearningLabel: "Estou a aprender",
        ytNativeLabel: "A minha língua materna",
        ytSelectPlaceholder: "Selecionar…",
        ytSearchingTitle: "A procurar legendas…",
        ytSearchingText: "A procurar legendas para este vídeo.",
        ytNoSubsTitle: "Nenhuma legenda disponível",
        ytNoSubsText: "Este vídeo não tem legendas. Experimente outro vídeo — nem todos os vídeos do YouTube têm legendas.",
        ytSearchAgain: "Procurar novamente",
        ytSignInToSave: "Inicie sessão para guardar palavras",
        ytSavedBadge: "guardado",
        ytWordsSaved: "{count} palavras guardadas",
    },
    ro: {
        ytSidebarTitle: "Subtitrări",
        ytOnboardingTitle: "Alege limbile",
        ytOnboardingText: "Alege limba pe care o înveți și limba ta maternă pentru a începe.",
        ytLearningLabel: "Învăț",
        ytNativeLabel: "Limba mea maternă",
        ytSelectPlaceholder: "Selectează…",
        ytSearchingTitle: "Se caută subtitrări…",
        ytSearchingText: "Se caută subtitrări pentru acest videoclip.",
        ytNoSubsTitle: "Nicio subtitrare disponibilă",
        ytNoSubsText: "Acest videoclip nu are subtitrări. Încearcă alt videoclip — nu toate videoclipurile de pe YouTube au subtitrări.",
        ytSearchAgain: "Caută din nou",
        ytSignInToSave: "Conectează-te pentru a salva cuvinte",
        ytSavedBadge: "salvat",
        ytWordsSaved: "{count} cuvinte salvate",
    },
    ru: {
        ytSidebarTitle: "Субтитры",
        ytOnboardingTitle: "Выберите языки",
        ytOnboardingText: "Укажите изучаемый язык и ваш родной язык, чтобы начать.",
        ytLearningLabel: "Я изучаю",
        ytNativeLabel: "Мой родной язык",
        ytSelectPlaceholder: "Выберите…",
        ytSearchingTitle: "Поиск субтитров…",
        ytSearchingText: "Ищем субтитры для этого видео.",
        ytNoSubsTitle: "Субтитры недоступны",
        ytNoSubsText: "У этого видео нет субтитров. Попробуйте другое видео — не у каждого видео на YouTube есть субтитры.",
        ytSearchAgain: "Искать снова",
        ytSignInToSave: "Войдите, чтобы сохранять слова",
        ytSavedBadge: "сохранено",
        ytWordsSaved: "{count} слова сохранено",
    },
    sk: {
        ytSidebarTitle: "Titulky",
        ytOnboardingTitle: "Vyberte jazyky",
        ytOnboardingText: "Vyberte jazyk, ktorý sa učíte, a svoj rodný jazyk, aby ste mohli začať.",
        ytLearningLabel: "Učím sa",
        ytNativeLabel: "Môj rodný jazyk",
        ytSelectPlaceholder: "Vybrať…",
        ytSearchingTitle: "Hľadanie titulkov…",
        ytSearchingText: "Hľadanie titulkov k tomuto videu.",
        ytNoSubsTitle: "Žiadne titulky nie sú k dispozícii",
        ytNoSubsText: "Toto video nemá titulky. Skúste iné video — nie každé video na YouTube má titulky.",
        ytSearchAgain: "Hľadať znova",
        ytSignInToSave: "Prihláste sa pre ukladanie slov",
        ytSavedBadge: "uložené",
        ytWordsSaved: "Uložených slov: {count}",
    },
    sl: {
        ytSidebarTitle: "Podnapisi",
        ytOnboardingTitle: "Izberite jezike",
        ytOnboardingText: "Izberite jezik, ki se ga učite, in svoj materni jezik za začetek.",
        ytLearningLabel: "Učim se",
        ytNativeLabel: "Moj materni jezik",
        ytSelectPlaceholder: "Izberite…",
        ytSearchingTitle: "Iskanje podnapisov…",
        ytSearchingText: "Iskanje podnapisov za ta videoposnetek.",
        ytNoSubsTitle: "Podnapisi niso na voljo",
        ytNoSubsText: "Ta videoposnetek nima podnapisov. Poskusite z drugim videoposnetkom — nimajo vsi videoposnetki na YouTubu podnapisov.",
        ytSearchAgain: "Iskanje znova",
        ytSignInToSave: "Prijavite se za shranjevanje besed",
        ytSavedBadge: "shranjeno",
        ytWordsSaved: "Shranjenih besed: {count}",
    },
    sr: {
        ytSidebarTitle: "Титлови",
        ytOnboardingTitle: "Изаберите језике",
        ytOnboardingText: "Изаберите језик који учите и свој матерњи језик да бисте почели.",
        ytLearningLabel: "Учим",
        ytNativeLabel: "Мој матерњи језик",
        ytSelectPlaceholder: "Изаберите…",
        ytSearchingTitle: "Тражење титлова…",
        ytSearchingText: "Тражење титлова за овај видео.",
        ytNoSubsTitle: "Нема доступних титлова",
        ytNoSubsText: "Овај видео нема титлове. Покушајте други видео — немају сви видеи на YouTube-у титлове.",
        ytSearchAgain: "Тражи поново",
        ytSignInToSave: "Пријавите се да сачувате речи",
        ytSavedBadge: "сачувано",
        ytWordsSaved: "Сачувано речи: {count}",
    },
    sv: {
        ytSidebarTitle: "Undertexter",
        ytOnboardingTitle: "Välj dina språk",
        ytOnboardingText: "Välj språket du lär dig och ditt modersmål för att börja.",
        ytLearningLabel: "Jag lär mig",
        ytNativeLabel: "Mitt modersmål",
        ytSelectPlaceholder: "Välj…",
        ytSearchingTitle: "Söker efter undertexter…",
        ytSearchingText: "Söker efter undertexter för den här videon.",
        ytNoSubsTitle: "Inga undertexter tillgängliga",
        ytNoSubsText: "Den här videon har inga undertexter. Prova en annan video — alla videor på YouTube har inte undertexter.",
        ytSearchAgain: "Sök igen",
        ytSignInToSave: "Logga in för att spara ord",
        ytSavedBadge: "sparat",
        ytWordsSaved: "{count} ord sparade",
    },
    sw: {
        ytSidebarTitle: "Manukuu",
        ytOnboardingTitle: "Chagua lugha zako",
        ytOnboardingText: "Chagua lugha unayojifunza na lugha yako ya asili ili kuanza.",
        ytLearningLabel: "Ninajifunza",
        ytNativeLabel: "Lugha yangu ya asili",
        ytSelectPlaceholder: "Chagua…",
        ytSearchingTitle: "Inatafuta manukuu…",
        ytSearchingText: "Inatafuta manukuu ya video hii.",
        ytNoSubsTitle: "Hakuna manukuu yanayopatikana",
        ytNoSubsText: "Video hii haina manukuu. Jaribu video nyingine — si kila video kwenye YouTube ina manukuu.",
        ytSearchAgain: "Tafuta tena",
        ytSignInToSave: "Ingia ili kuhifadhi maneno",
        ytSavedBadge: "imehifadhiwa",
        ytWordsSaved: "Maneno {count} yamehifadhiwa",
    },
    ta: {
        ytSidebarTitle: "வசன வரிகள்",
        ytOnboardingTitle: "உங்கள் மொழிகளைத் தேர்ந்தெடுக்கவும்",
        ytOnboardingText: "தொடங்க, நீங்கள் கற்கும் மொழியையும் உங்கள் தாய்மொழியையும் தேர்ந்தெடுக்கவும்.",
        ytLearningLabel: "நான் கற்கிறேன்",
        ytNativeLabel: "எனது தாய்மொழி",
        ytSelectPlaceholder: "தேர்ந்தெடுக்கவும்…",
        ytSearchingTitle: "வசன வரிகள் தேடப்படுகின்றன…",
        ytSearchingText: "இந்த வீடியோவுக்கான வசன வரிகள் தேடப்படுகின்றன.",
        ytNoSubsTitle: "வசன வரிகள் எதுவும் இல்லை",
        ytNoSubsText: "இந்த வீடியோவில் வசன வரிகள் இல்லை. வேறு வீடியோவை முயற்சிக்கவும் — YouTube இல் உள்ள எல்லா வீடியோக்களிலும் வசன வரிகள் இருக்காது.",
        ytSearchAgain: "மீண்டும் தேடு",
        ytSignInToSave: "சொற்களைச் சேமிக்க உள்நுழையவும்",
        ytSavedBadge: "சேமிக்கப்பட்டது",
        ytWordsSaved: "{count} சொற்கள் சேமிக்கப்பட்டன",
    },
    te: {
        ytSidebarTitle: "ఉపశీర్షికలు",
        ytOnboardingTitle: "మీ భాషలను ఎంచుకోండి",
        ytOnboardingText: "ప్రారంభించడానికి మీరు నేర్చుకుంటున్న భాషను మరియు మీ మాతృభాషను ఎంచుకోండి.",
        ytLearningLabel: "నేను నేర్చుకుంటున్నాను",
        ytNativeLabel: "నా మాతృభాష",
        ytSelectPlaceholder: "ఎంచుకోండి…",
        ytSearchingTitle: "ఉపశీర్షికల కోసం వెతుకుతోంది…",
        ytSearchingText: "ఈ వీడియో కోసం ఉపశీర్షికల కోసం వెతుకుతోంది.",
        ytNoSubsTitle: "ఉపశీర్షికలు అందుబాటులో లేవు",
        ytNoSubsText: "ఈ వీడియోకి ఉపశీర్షికలు లేవు. మరో వీడియోని ప్రయత్నించండి — YouTubeలో ప్రతి వీడియోకి ఉపశీర్షికలు ఉండవు.",
        ytSearchAgain: "మళ్లీ వెతకండి",
        ytSignInToSave: "పదాలను సేవ్ చేయడానికి సైన్ ఇన్ చేయండి",
        ytSavedBadge: "సేవ్ చేయబడింది",
        ytWordsSaved: "{count} పదాలు సేవ్ చేయబడ్డాయి",
    },
    th: {
        ytSidebarTitle: "คำบรรยาย",
        ytOnboardingTitle: "เลือกภาษาของคุณ",
        ytOnboardingText: "เลือกภาษาที่คุณกำลังเรียนและภาษาแม่ของคุณเพื่อเริ่มต้น",
        ytLearningLabel: "ฉันกำลังเรียน",
        ytNativeLabel: "ภาษาแม่ของฉัน",
        ytSelectPlaceholder: "เลือก…",
        ytSearchingTitle: "กำลังค้นหาคำบรรยาย…",
        ytSearchingText: "กำลังค้นหาคำบรรยายสำหรับวิดีโอนี้",
        ytNoSubsTitle: "ไม่มีคำบรรยาย",
        ytNoSubsText: "วิดีโอนี้ไม่มีคำบรรยาย ลองวิดีโออื่น — ไม่ใช่ทุกวิดีโอบน YouTube ที่มีคำบรรยาย",
        ytSearchAgain: "ค้นหาอีกครั้ง",
        ytSignInToSave: "ลงชื่อเข้าใช้เพื่อบันทึกคำศัพท์",
        ytSavedBadge: "บันทึกแล้ว",
        ytWordsSaved: "บันทึก {count} คำ",
    },
    tr: {
        ytSidebarTitle: "Altyazılar",
        ytOnboardingTitle: "Dillerinizi seçin",
        ytOnboardingText: "Başlamak için öğrendiğiniz dili ve ana dilinizi seçin.",
        ytLearningLabel: "Öğreniyorum",
        ytNativeLabel: "Ana dilim",
        ytSelectPlaceholder: "Seçin…",
        ytSearchingTitle: "Altyazılar aranıyor…",
        ytSearchingText: "Bu video için altyazılar aranıyor.",
        ytNoSubsTitle: "Kullanılabilir altyazı yok",
        ytNoSubsText: "Bu videoda altyazı yok. Başka bir video deneyin — YouTube'daki her videoda altyazı bulunmaz.",
        ytSearchAgain: "Tekrar ara",
        ytSignInToSave: "Kelimeleri kaydetmek için giriş yapın",
        ytSavedBadge: "kaydedildi",
        ytWordsSaved: "{count} kelime kaydedildi",
    },
    uk: {
        ytSidebarTitle: "Субтитри",
        ytOnboardingTitle: "Виберіть мови",
        ytOnboardingText: "Вкажіть мову, яку вивчаєте, і вашу рідну мову, щоб почати.",
        ytLearningLabel: "Я вивчаю",
        ytNativeLabel: "Моя рідна мова",
        ytSelectPlaceholder: "Виберіть…",
        ytSearchingTitle: "Пошук субтитрів…",
        ytSearchingText: "Шукаємо субтитри для цього відео.",
        ytNoSubsTitle: "Субтитри недоступні",
        ytNoSubsText: "У цього відео немає субтитрів. Спробуйте інше відео — не кожне відео на YouTube має субтитри.",
        ytSearchAgain: "Шукати знову",
        ytSignInToSave: "Увійдіть, щоб зберігати слова",
        ytSavedBadge: "збережено",
        ytWordsSaved: "Збережено слів: {count}",
    },
    vi: {
        ytSidebarTitle: "Phụ đề",
        ytOnboardingTitle: "Chọn ngôn ngữ của bạn",
        ytOnboardingText: "Chọn ngôn ngữ bạn đang học và tiếng mẹ đẻ của bạn để bắt đầu.",
        ytLearningLabel: "Tôi đang học",
        ytNativeLabel: "Tiếng mẹ đẻ của tôi",
        ytSelectPlaceholder: "Chọn…",
        ytSearchingTitle: "Đang tìm phụ đề…",
        ytSearchingText: "Đang tìm phụ đề cho video này.",
        ytNoSubsTitle: "Không có phụ đề",
        ytNoSubsText: "Video này không có phụ đề. Hãy thử video khác — không phải video nào trên YouTube cũng có phụ đề.",
        ytSearchAgain: "Tìm lại",
        ytSignInToSave: "Đăng nhập để lưu từ vựng",
        ytSavedBadge: "đã lưu",
        ytWordsSaved: "Đã lưu {count} từ",
    },
    "zh_CN": {
        ytSidebarTitle: "字幕",
        ytOnboardingTitle: "选择您的语言",
        ytOnboardingText: "选择您正在学习的语言和您的母语以开始。",
        ytLearningLabel: "我正在学习",
        ytNativeLabel: "我的母语",
        ytSelectPlaceholder: "选择…",
        ytSearchingTitle: "正在查找字幕…",
        ytSearchingText: "正在查找此视频的字幕。",
        ytNoSubsTitle: "没有可用的字幕",
        ytNoSubsText: "此视频没有字幕。请尝试其他视频——并非所有 YouTube 视频都有字幕。",
        ytSearchAgain: "重新查找",
        ytSignInToSave: "登录以保存单词",
        ytSavedBadge: "已保存",
        ytWordsSaved: "已保存 {count} 个单词",
    },
    "zh_TW": {
        ytSidebarTitle: "字幕",
        ytOnboardingTitle: "選擇您的語言",
        ytOnboardingText: "選擇您正在學習的語言和您的母語以開始。",
        ytLearningLabel: "我正在學習",
        ytNativeLabel: "我的母語",
        ytSelectPlaceholder: "選擇…",
        ytSearchingTitle: "正在尋找字幕…",
        ytSearchingText: "正在尋找此影片的字幕。",
        ytNoSubsTitle: "沒有可用的字幕",
        ytNoSubsText: "此影片沒有字幕。請嘗試其他影片——並非所有 YouTube 影片都有字幕。",
        ytSearchAgain: "重新尋找",
        ytSignInToSave: "登入以儲存單字",
        ytSavedBadge: "已儲存",
        ytWordsSaved: "已儲存 {count} 個單字",
    },
};
