// Canned subtitle lines for promo demo mode — one 10-line set per language.
//
// Index i of every language's array is the SAME sentence, so any two languages
// can be paired as (learning, native) tracks for a localized promo screenshot.
// English is the source; the rest are translations. Keys are language codes;
// the region is kept only where the script differs (zh_CN vs zh_TW). Everything
// else is keyed by the base code (e.g. 'pt' serves pt_BR and pt_PT).
//
// Adding a language = add one entry with 10 lines in the same order. Missing
// languages fall back to English via demoLinesFor().
//
// Generated from promo translation data; edit the source rather than by hand.

export const DEMO_LINE_COUNT = 10;

export const DEMO_SUBS_BY_LANG: Record<string, string[]> = {
    en: [
        "Hey, how are you? Glad to see you",
        "Today we'll learn something fun",
        "Listen calmly and repeat with me",
        "See how this word is pronounced",
        "Don't worry if you make a mistake",
        "Every day you understand a little more",
        "Save the words you don't know yet",
        "You're doing really well!",
        "Let's keep practicing together",
        "See you in the next video",
    ],
    es: [
        "Hola, ¿qué tal? Me alegro de verte",
        "Hoy vamos a aprender algo divertido",
        "Escucha con calma y repite conmigo",
        "Mira cómo se pronuncia esta palabra",
        "No te preocupes si te equivocas",
        "Cada día entiendes un poco más",
        "Guarda las palabras que no conozcas",
        "¡Lo estás haciendo muy bien!",
        "Sigamos practicando juntos",
        "Nos vemos en el próximo video",
    ],
    de: [
        "Hey, wie geht's? Schön, dich zu sehen",
        "Heute lernen wir was Schönes",
        "Hör in Ruhe zu und sprich mit mir nach",
        "Schau, wie dieses Wort ausgesprochen wird",
        "Keine Sorge, wenn du einen Fehler machst",
        "Jeden Tag verstehst du ein bisschen mehr",
        "Speichere dir die Wörter, die du noch nicht kennst",
        "Du machst das richtig gut!",
        "Lass uns weiter zusammen üben",
        "Bis zum nächsten Video",
    ],
    fr: [
        "Salut, comment ça va ? Content de te voir",
        "Aujourd'hui, on va apprendre un truc sympa",
        "Écoute tranquillement et répète avec moi",
        "Regarde comment ce mot se prononce",
        "Pas de panique si tu fais une erreur",
        "Chaque jour, tu comprends un peu plus",
        "Note les mots que tu ne connais pas encore",
        "Tu te débrouilles vraiment bien !",
        "Continuons à nous entraîner ensemble",
        "À très vite dans la prochaine vidéo",
    ],
    it: [
        "Ciao, come stai? Che bello vederti",
        "Oggi impariamo una cosa divertente",
        "Ascolta con calma e ripeti con me",
        "Guarda come si pronuncia questa parola",
        "Non preoccuparti se sbagli",
        "Ogni giorno capisci un po' di più",
        "Salva le parole che ancora non conosci",
        "Stai andando davvero bene!",
        "Continuiamo a esercitarci insieme",
        "Ci vediamo nel prossimo video",
    ],
    nl: [
        "Hé, hoe gaat het? Leuk om je te zien",
        "Vandaag leren we iets leuks",
        "Luister rustig en herhaal met mij",
        "Kijk hoe dit woord wordt uitgesproken",
        "Geen zorgen als je een fout maakt",
        "Elke dag begrijp je een beetje meer",
        "Bewaar de woorden die je nog niet kent",
        "Je doet het echt goed!",
        "Laten we samen blijven oefenen",
        "Tot in de volgende video",
    ],
    ca: [
        "Ei, com estàs? M'alegro de veure't",
        "Avui aprendrem una cosa divertida",
        "Escolta amb calma i repeteix amb mi",
        "Mira com es pronuncia aquesta paraula",
        "No et preocupis si t'equivoques",
        "Cada dia entens una mica més",
        "Desa les paraules que encara no coneixes",
        "Ho estàs fent molt bé!",
        "Continuem practicant junts",
        "Ens veiem al pròxim vídeo",
    ],
    pt: [
        "Oi, tudo bem? Que bom te ver",
        "Hoje vamos aprender uma coisa divertida",
        "Escuta com calma e repete comigo",
        "Veja como se pronuncia esta palavra",
        "Não te preocupes se cometeres um erro",
        "Cada dia você entende um pouco mais",
        "Guarda as palavras que ainda não conheces",
        "Você está indo muito bem!",
        "Vamos continuar praticando juntos",
        "Até o próximo vídeo",
    ],
    sv: [
        "Hej, hur mår du? Kul att se dig",
        "Idag ska vi lära oss något kul",
        "Lyssna lugnt och upprepa med mig",
        "Hör hur det här ordet uttalas",
        "Oroa dig inte om du gör ett fel",
        "Varje dag förstår du lite mer",
        "Spara orden du inte kan än",
        "Du gör det jättebra!",
        "Vi fortsätter öva tillsammans",
        "Vi ses i nästa video",
    ],
    da: [
        "Hej, hvordan går det? Godt at se dig",
        "I dag skal vi lære noget sjovt",
        "Lyt roligt og gentag med mig",
        "Hør hvordan det her ord udtales",
        "Bare rolig, hvis du laver en fejl",
        "Hver dag forstår du lidt mere",
        "Gem de ord, du ikke kan endnu",
        "Du gør det rigtig godt!",
        "Lad os blive ved med at øve sammen",
        "Vi ses i den næste video",
    ],
    no: [
        "Hei, hvordan går det? Hyggelig å se deg",
        "I dag skal vi lære noe gøy",
        "Lytt rolig og gjenta med meg",
        "Hør hvordan dette ordet uttales",
        "Ikke vær redd om du gjør en feil",
        "Hver dag forstår du litt mer",
        "Lagre ordene du ikke kan ennå",
        "Du gjør det kjempebra!",
        "La oss fortsette å øve sammen",
        "Vi ses i neste video",
    ],
    fi: [
        "Hei, mitä kuuluu? Kiva nähdä sinua",
        "Tänään opitaan jotain kivaa",
        "Kuuntele rauhassa ja toista perässäni",
        "Kuuntele, miten tämä sana lausutaan",
        "Älä huoli, jos teet virheen",
        "Joka päivä ymmärrät vähän enemmän",
        "Tallenna sanat, joita et vielä osaa",
        "Sinä pärjäät tosi hyvin!",
        "Jatketaan harjoittelua yhdessä",
        "Nähdään seuraavassa videossa",
    ],
    et: [
        "Tere, kuidas läheb? Tore sind näha",
        "Täna õpime midagi lõbusat",
        "Kuula rahulikult ja korda minu järel",
        "Kuula, kuidas seda sõna hääldatakse",
        "Ära muretse, kui teed vea",
        "Iga päevaga saad sa veidi rohkem aru",
        "Salvesta sõnad, mida sa veel ei tea",
        "Sul läheb tõesti hästi!",
        "Harjutame koos edasi",
        "Näeme järgmises videos",
    ],
    lv: [
        "Sveiks, kā tev klājas? Prieks tevi redzēt",
        "Šodien mēs iemācīsimies kaut ko jautru",
        "Klausies mierīgi un atkārto kopā ar mani",
        "Klausies, kā izrunā šo vārdu",
        "Neuztraucies, ja kļūdies",
        "Ar katru dienu tu saproti mazliet vairāk",
        "Saglabā vārdus, kurus vēl nezini",
        "Tev tiešām labi sanāk!",
        "Turpināsim vingrināties kopā",
        "Tiekamies nākamajā video",
    ],
    lt: [
        "Sveiki, kaip sekasi? Smagu tave matyti",
        "Šiandien išmoksime ką nors smagaus",
        "Klausykis ramiai ir kartok su manimi",
        "Klausyk, kaip tariamas šis žodis",
        "Nesijaudink, jei suklysi",
        "Kasdien supranti vis šiek tiek daugiau",
        "Išsaugok žodžius, kurių dar nemoki",
        "Tau tikrai puikiai sekasi!",
        "Toliau mokykimės kartu",
        "Iki pasimatymo kitame vaizdo įraše",
    ],
    pl: [
        "Cześć, jak się masz? Miło cię widzieć",
        "Dziś nauczymy się czegoś fajnego",
        "Słuchaj spokojnie i powtarzaj za mną",
        "Zobacz, jak wymawia się to słowo",
        "Nie martw się, jeśli zrobisz błąd",
        "Każdego dnia rozumiesz trochę więcej",
        "Zapisuj słowa, których jeszcze nie znasz",
        "Świetnie ci idzie!",
        "Ćwiczmy dalej razem",
        "Do zobaczenia w następnym filmie",
    ],
    cs: [
        "Ahoj, jak se máš? Rád tě vidím",
        "Dnes se naučíme něco zábavného",
        "Poslouchej v klidu a opakuj po mně",
        "Podívej se, jak se to slovo vyslovuje",
        "Neboj se, když uděláš chybu",
        "Každý den rozumíš o něco víc",
        "Ukládej si slovíčka, která ještě neznáš",
        "Jde ti to fakt skvěle!",
        "Cvičme dál společně",
        "Uvidíme se v dalším videu",
    ],
    sk: [
        "Ahoj, ako sa máš? Rád ťa vidím",
        "Dnes sa naučíme niečo zábavné",
        "Počúvaj v pokoji a opakuj po mne",
        "Pozri sa, ako sa to slovo vyslovuje",
        "Neboj sa, ak urobíš chybu",
        "Každý deň rozumieš o niečo viac",
        "Ukladaj si slovíčka, ktoré ešte nepoznáš",
        "Ide ti to naozaj skvele!",
        "Cvičme ďalej spolu",
        "Uvidíme sa v ďalšom videu",
    ],
    hu: [
        "Szia, hogy vagy? Örülök, hogy látlak",
        "Ma valami jót fogunk tanulni",
        "Hallgasd nyugodtan, és ismételd velem",
        "Nézd, hogyan kell kiejteni ezt a szót",
        "Ne aggódj, ha hibázol",
        "Minden nap egy kicsivel többet értesz",
        "Mentsd el a szavakat, amiket még nem ismersz",
        "Nagyon ügyes vagy!",
        "Gyakoroljunk tovább együtt",
        "Találkozunk a következő videóban",
    ],
    ro: [
        "Bună, ce mai faci? Mă bucur să te văd",
        "Azi învățăm ceva distractiv",
        "Ascultă liniștit și repetă după mine",
        "Uite cum se pronunță cuvântul ăsta",
        "Nu-ți face griji dacă greșești",
        "În fiecare zi înțelegi puțin mai mult",
        "Salvează cuvintele pe care încă nu le știi",
        "Te descurci foarte bine!",
        "Hai să exersăm în continuare împreună",
        "Ne vedem în următorul videoclip",
    ],
    hr: [
        "Bok, kako si? Drago mi je što te vidim",
        "Danas ćemo naučiti nešto zabavno",
        "Slušaj mirno i ponavljaj za mnom",
        "Pogledaj kako se izgovara ova riječ",
        "Ne brini ako pogriješiš",
        "Svaki dan razumiješ malo više",
        "Spremi riječi koje još ne znaš",
        "Stvarno ti dobro ide!",
        "Nastavimo vježbati zajedno",
        "Vidimo se u sljedećem videu",
    ],
    sl: [
        "Živjo, kako si? Vesel sem, da te vidim",
        "Danes se bomo naučili nekaj zabavnega",
        "Poslušaj mirno in ponavljaj za mano",
        "Poglej, kako se izgovori ta beseda",
        "Ne skrbi, če narediš napako",
        "Vsak dan razumeš malo več",
        "Shrani besede, ki jih še ne poznaš",
        "Res ti gre odlično!",
        "Vadiva naprej skupaj",
        "Se vidimo v naslednjem videu",
    ],
    ru: [
        "Привет, как дела? Рад тебя видеть",
        "Сегодня узнаем кое-что интересное",
        "Слушай спокойно и повторяй за мной",
        "Послушай, как произносится это слово",
        "Не переживай, если ошибёшься",
        "Каждый день ты понимаешь чуть больше",
        "Сохраняй слова, которых пока не знаешь",
        "У тебя отлично получается!",
        "Давай продолжим практиковаться вместе",
        "Увидимся в следующем видео",
    ],
    uk: [
        "Привіт, як справи? Радий тебе бачити",
        "Сьогодні дізнаємося щось цікаве",
        "Слухай спокійно і повторюй за мною",
        "Послухай, як вимовляється це слово",
        "Не хвилюйся, якщо помилишся",
        "Щодня ти розумієш трохи більше",
        "Зберігай слова, яких поки не знаєш",
        "У тебе чудово виходить!",
        "Продовжуймо практикуватися разом",
        "Побачимося в наступному відео",
    ],
    bg: [
        "Здравей, как си? Радвам се да те видя",
        "Днес ще научим нещо забавно",
        "Слушай спокойно и повтаряй с мен",
        "Чуй как се произнася тази дума",
        "Не се притеснявай, ако сгрешиш",
        "Всеки ден разбираш малко повече",
        "Запазвай думите, които още не знаеш",
        "Справяш се наистина добре!",
        "Нека продължим да упражняваме заедно",
        "Ще се видим в следващото видео",
    ],
    sr: [
        "Здраво, како си? Драго ми је да те видим",
        "Данас ћемо научити нешто забавно",
        "Слушај мирно и понављај за мном",
        "Послушај како се изговара ова реч",
        "Не брини ако погрешиш",
        "Сваког дана разумеш мало више",
        "Сачувај речи које још не знаш",
        "Заиста ти добро иде!",
        "Хајде да наставимо да вежбамо заједно",
        "Видимо се у следећем видеу",
    ],
    el: [
        "Γεια, τι κάνεις; Χαίρομαι που σε βλέπω",
        "Σήμερα θα μάθουμε κάτι διασκεδαστικό",
        "Άκου ήρεμα και επανάλαβε μαζί μου",
        "Άκου πώς προφέρεται αυτή η λέξη",
        "Μην ανησυχείς αν κάνεις λάθος",
        "Κάθε μέρα καταλαβαίνεις λίγο περισσότερο",
        "Αποθήκευε τις λέξεις που δεν ξέρεις ακόμα",
        "Τα πας πραγματικά πολύ καλά!",
        "Ας συνεχίσουμε να εξασκούμαστε μαζί",
        "Τα λέμε στο επόμενο βίντεο",
    ],
    tr: [
        "Selam, nasılsın? Seni gördüğüme sevindim",
        "Bugün eğlenceli bir şey öğreneceğiz",
        "Sakince dinle ve benimle tekrar et",
        "Bu kelimenin nasıl söylendiğini dinle",
        "Hata yaparsan endişelenme",
        "Her gün biraz daha fazla anlıyorsun",
        "Henüz bilmediğin kelimeleri kaydet",
        "Gerçekten çok iyi gidiyorsun!",
        "Hadi birlikte pratik yapmaya devam edelim",
        "Bir sonraki videoda görüşürüz",
    ],
    ar: [
        "مرحبًا، كيف حالك؟ سعيد برؤيتك",
        "اليوم سنتعلم شيئًا ممتعًا",
        "استمع بهدوء وكرّر معي",
        "شاهد كيف تُنطق هذه الكلمة",
        "لا تقلق إن أخطأت",
        "كل يوم تفهم أكثر قليلًا",
        "احفظ الكلمات التي لا تعرفها بعد",
        "أنت تبلي حسنًا حقًّا!",
        "لنواصل التدرّب معًا",
        "أراك في الفيديو القادم",
    ],
    fa: [
        "سلام، حالت چطوره؟ از دیدنت خوشحالم",
        "امروز یه چیز جالب یاد می‌گیریم",
        "با آرامش گوش بده و با من تکرار کن",
        "ببین این کلمه چطور تلفظ می‌شه",
        "نگران نباش اگه اشتباه کردی",
        "هر روز یه کم بیشتر می‌فهمی",
        "کلمه‌هایی رو که هنوز بلد نیستی ذخیره کن",
        "داری خیلی خوب پیش می‌ری!",
        "بیا با هم تمرین رو ادامه بدیم",
        "تو ویدیوی بعدی می‌بینمت",
    ],
    he: [
        "היי, מה שלומך? כיף לראות אותך",
        "היום נלמד משהו כיפי",
        "הקשב ברוגע וחזור איתי",
        "ראה איך מבטאים את המילה הזאת",
        "אל תדאג אם אתה טועה",
        "כל יום אתה מבין קצת יותר",
        "שמור את המילים שאתה עוד לא מכיר",
        "אתה ממש מצליח!",
        "בוא נמשיך להתאמן יחד",
        "נתראה בסרטון הבא",
    ],
    hi: [
        "हे, कैसे हो? तुम्हें देखकर अच्छा लगा",
        "आज हम कुछ मज़ेदार सीखेंगे",
        "आराम से सुनो और मेरे साथ दोहराओ",
        "देखो यह शब्द कैसे बोला जाता है",
        "गलती हो जाए तो चिंता मत करो",
        "हर दिन तुम थोड़ा और समझने लगते हो",
        "जो शब्द अभी नहीं आते उन्हें सेव कर लो",
        "तुम सच में बहुत अच्छा कर रहे हो!",
        "चलो साथ में अभ्यास करते रहें",
        "अगले वीडियो में मिलते हैं",
    ],
    bn: [
        "আরে, কেমন আছো? তোমাকে দেখে ভালো লাগল",
        "আজ আমরা মজার কিছু শিখব",
        "শান্তভাবে শোনো আর আমার সাথে বলো",
        "দেখো এই শব্দটা কীভাবে উচ্চারণ করে",
        "ভুল হলে চিন্তা কোরো না",
        "প্রতিদিন তুমি একটু একটু করে বোঝো",
        "যে শব্দগুলো এখনও জানো না সেগুলো সেভ করে রাখো",
        "তুমি সত্যিই খুব ভালো করছ!",
        "চলো একসাথে অনুশীলন চালিয়ে যাই",
        "পরের ভিডিওতে দেখা হবে",
    ],
    gu: [
        "અરે, કેમ છો? તમને જોઈને આનંદ થયો",
        "આજે આપણે કંઈક મજાનું શીખીશું",
        "શાંતિથી સાંભળો અને મારી સાથે બોલો",
        "જુઓ, આ શબ્દ કેવી રીતે બોલાય છે",
        "ભૂલ થાય તો ચિંતા ન કરો",
        "દરરોજ તમે થોડું વધારે સમજો છો",
        "જે શબ્દો હજી નથી આવડતા તે સાચવી રાખો",
        "તમે ખરેખર સરસ કરી રહ્યા છો!",
        "ચાલો સાથે મળીને પ્રેક્ટિસ કરતા રહીએ",
        "આવતા વીડિયોમાં મળીએ",
    ],
    kn: [
        "ಹಾಯ್, ಹೇಗಿದ್ದೀರಾ? ನಿಮ್ಮನ್ನು ನೋಡಿ ಖುಷಿಯಾಯಿತು",
        "ಇವತ್ತು ನಾವು ಏನಾದರೂ ಮಜವಾದದ್ದನ್ನು ಕಲಿಯೋಣ",
        "ಆರಾಮಾಗಿ ಕೇಳಿ, ನನ್ನ ಜೊತೆ ಪುನಃ ಹೇಳಿ",
        "ಈ ಪದವನ್ನು ಹೇಗೆ ಉಚ್ಚರಿಸ್ತಾರೆ ನೋಡಿ",
        "ತಪ್ಪು ಮಾಡಿದರೆ ಚಿಂತೆ ಮಾಡಬೇಡಿ",
        "ಪ್ರತಿದಿನ ನೀವು ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಅರ್ಥ ಮಾಡಿಕೊಳ್ತೀರಿ",
        "ಇನ್ನೂ ಗೊತ್ತಿಲ್ಲದ ಪದಗಳನ್ನು ಉಳಿಸಿಕೊಳ್ಳಿ",
        "ನೀವು ನಿಜವಾಗಿಯೂ ಚೆನ್ನಾಗಿ ಮಾಡ್ತಾ ಇದ್ದೀರಿ!",
        "ಒಟ್ಟಿಗೆ ಅಭ್ಯಾಸ ಮಾಡ್ತಾ ಇರೋಣ",
        "ಮುಂದಿನ ವಿಡಿಯೋದಲ್ಲಿ ಸಿಗೋಣ",
    ],
    ml: [
        "ഹായ്, സുഖമാണോ? കണ്ടതിൽ സന്തോഷം",
        "ഇന്ന് നമ്മൾ രസകരമായ ഒന്ന് പഠിക്കാം",
        "ശാന്തമായി കേൾക്കൂ, എന്റെ കൂടെ പറയൂ",
        "ഈ വാക്ക് എങ്ങനെ ഉച്ചരിക്കുന്നു എന്ന് നോക്കൂ",
        "തെറ്റ് വന്നാലും വിഷമിക്കേണ്ട",
        "ഓരോ ദിവസവും നിങ്ങൾ കുറച്ചുകൂടി മനസ്സിലാക്കുന്നു",
        "ഇതുവരെ അറിയാത്ത വാക്കുകൾ സേവ് ചെയ്യൂ",
        "നിങ്ങൾ ശരിക്കും നന്നായി ചെയ്യുന്നുണ്ട്!",
        "നമുക്ക് ഒരുമിച്ച് പരിശീലിച്ചുകൊണ്ടിരിക്കാം",
        "അടുത്ത വീഡിയോയിൽ കാണാം",
    ],
    mr: [
        "अरे, कसे आहात? तुम्हाला बघून छान वाटलं",
        "आज आपण काहीतरी मजेदार शिकूया",
        "शांतपणे ऐका आणि माझ्यासोबत म्हणा",
        "हा शब्द कसा उच्चारतात ते बघा",
        "चूक झाली तरी काळजी करू नका",
        "दररोज तुम्हाला थोडं अधिक समजतं",
        "अजून माहीत नसलेले शब्द जपून ठेवा",
        "तुम्ही खरंच छान करताय!",
        "चला, एकत्र सराव करत राहूया",
        "पुढच्या व्हिडिओत भेटूया",
    ],
    ta: [
        "ஹாய், எப்படி இருக்கீங்க? உங்களைப் பார்த்ததில் சந்தோஷம்",
        "இன்னைக்கு நாம ஏதாவது சுவாரஸ்யமா கத்துக்கலாம்",
        "நிதானமா கேளுங்க, என்னோட சேர்ந்து சொல்லுங்க",
        "இந்த வார்த்தையை எப்படி உச்சரிக்கிறாங்கன்னு பாருங்க",
        "தப்பு பண்ணினாலும் கவலைப்படாதீங்க",
        "தினமும் கொஞ்சம் கூடுதலா புரிஞ்சுக்குறீங்க",
        "இன்னும் தெரியாத வார்த்தைகளை சேமிச்சு வைங்க",
        "நீங்க ரொம்ப நல்லா பண்றீங்க!",
        "சேர்ந்து பயிற்சி பண்ணிட்டே இருக்கலாம்",
        "அடுத்த வீடியோவில் சந்திக்கலாம்",
    ],
    te: [
        "హాయ్, ఎలా ఉన్నారు? మిమ్మల్ని చూసి సంతోషం",
        "ఈరోజు మనం ఏదైనా సరదాగా నేర్చుకుందాం",
        "ప్రశాంతంగా వినండి, నాతో పాటు చెప్పండి",
        "ఈ పదాన్ని ఎలా ఉచ్చరిస్తారో చూడండి",
        "తప్పు చేసినా బాధపడకండి",
        "ప్రతిరోజూ మీరు కొంచెం ఎక్కువ అర్థం చేసుకుంటారు",
        "ఇంకా తెలియని పదాలను సేవ్ చేసుకోండి",
        "మీరు నిజంగా బాగా చేస్తున్నారు!",
        "కలిసి ప్రాక్టీస్ చేస్తూ ఉందాం",
        "తదుపరి వీడియోలో కలుద్దాం",
    ],
    th: [
        "สวัสดี เป็นไงบ้าง? ดีใจที่ได้เจอนะ",
        "วันนี้เรามาเรียนอะไรสนุก ๆ กัน",
        "ฟังสบาย ๆ แล้วพูดตามฉันนะ",
        "มาดูกันว่าคำนี้ออกเสียงยังไง",
        "ไม่ต้องกังวลถ้าพูดผิดนะ",
        "ทุกวันเธอจะเข้าใจมากขึ้นทีละนิด",
        "เก็บคำที่ยังไม่รู้เอาไว้นะ",
        "เธอทำได้ดีมากเลย!",
        "มาฝึกกันต่อไปนะ",
        "เจอกันใหม่คลิปหน้านะ",
    ],
    vi: [
        "Chào bạn, bạn khỏe không? Vui được gặp bạn",
        "Hôm nay mình sẽ học một điều thú vị",
        "Cứ nghe thật thoải mái rồi lặp lại với mình nhé",
        "Xem từ này phát âm thế nào nhé",
        "Đừng lo nếu bạn mắc lỗi nhé",
        "Mỗi ngày bạn lại hiểu thêm một chút",
        "Lưu lại những từ bạn chưa biết nhé",
        "Bạn làm tốt lắm đấy!",
        "Mình cùng luyện tập tiếp nhé",
        "Hẹn gặp lại bạn ở video sau",
    ],
    id: [
        "Hai, apa kabar? Senang bertemu denganmu",
        "Hari ini kita akan belajar sesuatu yang seru",
        "Dengarkan dengan santai dan ulangi bersamaku",
        "Lihat bagaimana kata ini diucapkan",
        "Jangan khawatir kalau kamu salah",
        "Setiap hari kamu jadi mengerti sedikit lebih banyak",
        "Simpan kata-kata yang belum kamu tahu",
        "Kamu hebat sekali!",
        "Yuk, kita terus berlatih bersama",
        "Sampai jumpa di video berikutnya",
    ],
    ms: [
        "Hai, apa khabar? Gembira jumpa awak",
        "Hari ini kita akan belajar sesuatu yang seronok",
        "Dengar dengan tenang dan ulang bersama saya",
        "Lihat bagaimana perkataan ini disebut",
        "Jangan risau kalau awak buat silap",
        "Setiap hari awak faham sedikit demi sedikit",
        "Simpan perkataan yang awak belum tahu",
        "Awak buat dengan sangat baik!",
        "Jom kita terus berlatih bersama",
        "Jumpa lagi dalam video seterusnya",
    ],
    fil: [
        "Uy, kumusta ka? Ang saya makita ka",
        "Ngayon, may matututunan tayong masaya",
        "Makinig ka lang nang kalmado at ulitin mo kasama ko",
        "Tingnan natin kung paano bigkasin ang salitang ito",
        "Huwag kang mag-alala kung magkamali ka",
        "Araw-araw, kaunti-kaunti mo nang naiintindihan",
        "I-save mo ang mga salitang hindi mo pa alam",
        "Ang galing-galing mo!",
        "Tuloy-tuloy lang tayong magsanay",
        "Hanggang sa susunod nating video",
    ],
    sw: [
        "Habari yako? Nimefurahi kukuona",
        "Leo tutajifunza kitu cha kufurahisha",
        "Sikiliza kwa utulivu na urudie pamoja nami",
        "Angalia jinsi neno hili linavyotamkwa",
        "Usijali ukikosea",
        "Kila siku unaelewa zaidi kidogo kidogo",
        "Hifadhi maneno usiyoyajua bado",
        "Unafanya vizuri sana!",
        "Tuendelee kufanya mazoezi pamoja",
        "Tutaonana kwenye video inayofuata",
    ],
    ja: [
        "やあ、元気? 会えてうれしいよ",
        "今日は楽しいことを学ぼう",
        "落ち着いて聞いて、一緒に繰り返してね",
        "この単語の発音を見てみよう",
        "間違えても気にしないで",
        "毎日少しずつ分かるようになるよ",
        "まだ知らない単語は保存しておこう",
        "すごく上手だよ!",
        "一緒に練習を続けよう",
        "また次の動画で会おう",
    ],
    ko: [
        "안녕, 잘 지냈어? 만나서 반가워",
        "오늘은 재미있는 걸 배워 볼 거야",
        "편하게 듣고 나랑 같이 따라 해 봐",
        "이 단어가 어떻게 발음되는지 봐",
        "실수해도 걱정하지 마",
        "매일 조금씩 더 이해하게 될 거야",
        "아직 모르는 단어는 저장해 둬",
        "정말 잘하고 있어!",
        "우리 같이 계속 연습하자",
        "다음 영상에서 만나",
    ],
    "zh_CN": [
        "嘿,你好吗?见到你真高兴",
        "今天我们来学点有趣的",
        "静下心来听,跟我一起读",
        "看看这个词怎么读",
        "说错了也别担心",
        "每天你都会多懂一点",
        "把还不认识的词存下来",
        "你做得真的很棒!",
        "咱们继续一起练习吧",
        "下个视频再见",
    ],
    "zh_TW": [
        "嘿,你好嗎?見到你真開心",
        "今天我們來學點有趣的",
        "靜下心來聽,跟我一起念",
        "看看這個詞怎麼念",
        "說錯了也別擔心",
        "每天你都會多懂一點",
        "把還不認識的詞存起來",
        "你做得真的很棒!",
        "我們繼續一起練習吧",
        "下支影片再見",
    ],
    am: [
        "ሰላም፣ እንዴት ነህ? ስላገኘሁህ ደስ ብሎኛል",
        "ዛሬ አንድ አስደሳች ነገር እንማራለን",
        "በእርጋታ አዳምጥና ከእኔ ጋር ድገም",
        "ይህ ቃል እንዴት እንደሚነበብ ተመልከት",
        "ብትሳሳት አትጨነቅ",
        "በየቀኑ ትንሽ ተጨማሪ ትረዳለህ",
        "ገና የማታውቃቸውን ቃላት አስቀምጥ",
        "በጣም ጥሩ እየሰራህ ነው!",
        "አብረን መለማመዳችንን እንቀጥል",
        "በሚቀጥለው ቪዲዮ እንገናኝ",
    ],
};

/** Base language code (drops region/script suffix): 'zh_CN' → 'zh', 'pt_BR' → 'pt'. */
export function baseLangCode(code: string): string {
    return (code || '').split(/[-_]/)[0].toLowerCase();
}

/** The 10 demo lines for a code, falling back to the base code, then English. */
export function demoLinesFor(code: string): string[] {
    return (
        DEMO_SUBS_BY_LANG[code] ||
        DEMO_SUBS_BY_LANG[baseLangCode(code)] ||
        DEMO_SUBS_BY_LANG.en
    );
}
