import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Gaps between what the product does and what someone would reasonably expect,
 * pinned rather than fixed.
 *
 * Each one is a decision waiting to be made, not a defect waiting to be caught.
 * Pinning them means that closing one — or widening one by accident — shows up
 * as a failing check and a deliberate edit, instead of drifting quietly.
 *
 * These read the source and stylesheet, so they need no browser and run in
 * milliseconds.
 */

const REPO = join(__dirname, '..', '..', '..');
const read = (p: string) => readFileSync(join(__dirname, '..', p), 'utf8');
const sharedRead = (p: string) => readFileSync(join(__dirname, '..', '..', '..', 'packages', 'shared', p), 'utf8');

describe('right-to-left languages are not laid out right-to-left', () => {
    /**
     * Behaviour map §45. Arabic, Hebrew, Persian and Urdu render their text
     * right-to-left inside a left-to-right layout: the controls, the panel and
     * the reading order stay as they are.
     *
     * The one place mirroring DOES happen is the promotional-screenshot mode,
     * which is why a search for "rtl" in the source finds something and could
     * mislead someone into thinking this is handled.
     */
    test('mirroring exists only for promotional screenshots, not for readers', () => {
        const src = read('src/content/index.ts');

        // It is there...
        expect(src).toContain("'rtl'");

        // ...but only inside the demo path, gated on a demo-only list.
        const rtlLines = src
            .split('\n')
            .map((line, i) => [i + 1, line] as const)
            .filter(([, line]) => line.includes("'rtl'"));

        expect(rtlLines.length).toBeGreaterThan(0);
        for (const [, line] of rtlLines) {
            expect(line).toMatch(/isRTL/);
        }
        // The flag itself comes from the demo list, not from the reader's own
        // language. If this stops being true, real RTL support arrived and this
        // check should be updated deliberately.
        expect(src).toMatch(/const isRTL = DEMO_RTL\.has\(/);
    });
});

describe('no layout adaptation for narrow windows', () => {
    /**
     * Behaviour map §51. An absence rather than a behaviour: the panel is a
     * fixed width and nothing responds to the window getting narrow.
     */
    test('the stylesheet carries no width breakpoints', () => {
        const css = readFileSync(
            join(__dirname, '..', '..', 'rezka', 'src', 'assets', 'styles.css'),
            'utf8',
        );
        const widthQueries = css.match(/@media[^{]*(max-width|min-width)[^{]*/g) ?? [];
        expect(widthQueries).toEqual([]);
    });
});

describe('installing and uninstalling both open a web page', () => {
    /**
     * Behaviour map §31. Both moments send the person to a page on the product's
     * own site, and neither is mentioned in the privacy policy.
     *
     * Real installs and uninstalls cannot be driven by a test, so this pins the
     * wiring instead: that both are registered at all.
     */
    test('both moments are wired to a page', () => {
        const src = sharedRead('/src/onboarding.ts');
        expect(src).toMatch(/chrome\.runtime\.onInstalled\.addListener/);
        expect(src).toMatch(/chrome\.runtime\.setUninstallURL/);
    });
});

describe('the privacy policy and what the product actually does', () => {
    /**
     * Behaviour map §30. Looking a word up sends that word, and the sentence it
     * came from, whether or not anyone is signed in — so the policy has to say
     * so. It did not until 2026-09-06, when the summary still read "collects
     * nothing about you" and the words "dictionary" and "lookup" appeared in it
     * nowhere.
     *
     * The check was inverted rather than deleted when the policy was fixed: it
     * now fails if that disclosure is ever removed or the old absolute claim
     * comes back.
     */
    test('the policy describes word lookup, and no longer claims to collect nothing', () => {
        const policy = readFileSync(
            join(__dirname, '..', '..', '..', 'PRIVACY_POLICY.md'),
            'utf8',
        ).toLowerCase();

        expect(policy).toContain('dictionary');
        expect(policy).toContain('lookup');
        // The lookup runs signed out, so the policy must not promise otherwise.
        expect(policy).not.toContain('collects nothing about you');
        // And it must say that the analytics switch does NOT govern it. Matched
        // across whitespace: the sentence wraps in the source.
        expect(policy.replace(/\s+/g, ' ')).toMatch(/switch does not stop it/);
    });
});

describe('automatic captions are not marked as such', () => {
    /**
     * Behaviour map §47. YouTube tells us which caption tracks it generated by
     * machine, and the product carries that information all the way from the
     * site — and then never shows it. A learner reading unpunctuated,
     * lower-accuracy text has no way to know that is what they are reading.
     */
    test('the site tells us, and we keep it to ourselves', () => {
        // It arrives and is passed along...
        const pageScript = read('src/content/page-script.ts');
        expect(pageScript).toMatch(/kind: t\.kind/);

        // ...and then nothing that draws the interface ever consults it.
        const sidebar = sharedRead('/src/SidebarUI.ts');
        const app = read('src/content/app-base.ts');
        expect(sidebar).not.toMatch(/\.kind\b/);
        expect(app).not.toMatch(/\.kind\b/);
    });
});

describe('what the usage-statistics switch does not stop', () => {
    /**
     * Behaviour map §32. Turning statistics off is widely read as "stop sending
     * things about me". It stops the analytics, and nothing else: looking a word
     * up still reaches a server either way.
     *
     * Pinned by scope — the consent flag is consulted only by the analytics
     * code and the two places that offer the switch. The day something else
     * starts reading it, that is a deliberate widening and this check says so.
     */
    test('the consent flag governs analytics only', () => {
        // The complete list. Anything reading the flag outside it is a widening
        // of what the switch governs, which is a decision, not a refactor.
        const readers = [
            'packages/shared/src/prefs.ts', // where it is defined
            'packages/shared/src/SidebarUI.ts', // the switch in settings
            'packages/shared/src/analytics-bg.ts', // the gate it exists for
            'packages/shared/src/popup/popup.ts', // the same switch in the popup
        ];

        // Walk both source trees rather than reading four files: a new reader
        // is only caught by looking where nobody put one yet.
        const roots = ['packages/shared/src', 'apps/youtube/src'];
        const found: string[] = [];
        const walk = (dir: string): void => {
            for (const e of readdirSync(join(REPO, dir), { withFileTypes: true })) {
                const rel = `${dir}/${e.name}`;
                if (e.isDirectory()) walk(rel);
                else if (e.name.endsWith('.ts') && readFileSync(join(REPO, rel), 'utf8').includes('analyticsEnabled'))
                    found.push(rel);
            }
        };
        roots.forEach(walk);

        expect(found.sort()).toEqual([...readers].sort());

        // Word lookup is deliberately absent from that list — the sweep above
        // proves it, and this says why it matters if it ever appears.
        expect(found).not.toContain('packages/shared/src/lookup/strip.ts');
    });
});

describe('what is measured about people', () => {
    /**
     * Behaviour map §33. The measurements are product analytics, not error
     * counting: how many people come back on the second, seventh and
     * fourteenth day, and how far they get through setting the product up.
     *
     * That is more than most people assume "anonymous usage statistics" means,
     * so the list is pinned. Adding to it should be a deliberate act.
     */
    test('the measured list still covers retention and the setup funnel', () => {
        const analytics = sharedRead('/src/analytics.ts');
        for (const event of ['retained_d2', 'retained_d7', 'retained_d14']) {
            expect(analytics).toContain(event);
        }
    });
});

describe('anonymous measurements cannot be traced to a person', () => {
    /**
     * Behaviour map §34. Because nothing identifying is attached, a request to
     * delete "my" measurements cannot be honoured — there is nothing to look
     * up. That is a real limitation, and it is also the thing that makes the
     * measurements genuinely anonymous.
     *
     * This pins the mechanical guard rather than the promise: a list of names
     * that must never reach a payload, so one careless spread breaks a check
     * instead of the privacy policy.
     */
    test('identifying names are refused mechanically, not by discipline', () => {
        const analytics = sharedRead('/src/analytics.ts');
        for (const denied of ['uid', 'email', 'id_token', 'refresh_token']) {
            expect(analytics).toMatch(new RegExp(`'${denied}'`));
        }
        // The saved word and the line it came from are content, never telemetry.
        for (const denied of ['term', 'context', 'text']) {
            expect(analytics).toMatch(new RegExp(`'${denied}'`));
        }
    });
});

describe('choosing the same language for both slots', () => {
    /**
     * Behaviour map §46, and the map's own wording needed correcting here:
     * nothing is "silently substituted". What actually happens is that only ONE
     * track is asked for, so the reader ends up in a product built around two
     * languages showing one, with nothing said about why.
     *
     * Nothing prevents the choice in the first place, which is the decision
     * worth taking: refuse it, warn about it, or leave it.
     */
    test('only one track is requested, and nothing explains why', () => {
        const plan = read('src/content/trackPlan.ts');

        // The second request is made only when the two differ...
        expect(plan).toMatch(/if \(prefs\.native !== prefs\.learning\) \{/);

        // ...and there is no warning, refusal, or substitution anywhere near it.
        expect(plan).not.toMatch(/warn|refuse|substitut/i);
    });
});

describe('diagnostic reports are narrower than the store promises', () => {
    /**
     * Behaviour map §35. The store listing offers one click to report a
     * problem. The policy is narrower, and the policy is the accurate one:
     * reports go only while signed in, and only once per account per day.
     *
     * A person who is signed out, or who already reported today, presses the
     * button and nothing is sent — with nothing said about it.
     *
     * Pinned against the policy text, which is the document that has to stay
     * true. If the limits change, this fails and the listing needs revisiting
     * at the same time.
     */
    test('the policy still states both limits', () => {
        const policy = readFileSync(
            join(__dirname, '..', '..', '..', 'PRIVACY_POLICY.md'),
            'utf8',
        );

        expect(policy).toMatch(/sent only while you are signed in/i);
        expect(policy).toMatch(/capped at one per account per day/i);
    });
});

describe('announcements from the product team', () => {
    /**
     * Behaviour map §22. A message arrives from a server, so one cannot be
     * summoned on demand without standing up test content — the live checks
     * therefore do not cover it.
     *
     * What can be pinned without a server is the contract that matters most:
     * a dismissed message must never come back. That is stored, and the
     * storage is what a returning message would have to get past.
     */
    test('a dismissed message is remembered, and failures are silent by design', () => {
        const notifications = sharedRead('/src/notifications.ts');

        // Dismissals are kept, which is what stops a message returning.
        expect(notifications).toMatch(/notif\.dismissed/);

        // The list is pruned once a message is gone, so it cannot grow for the
        // life of the installation.
        expect(notifications).toMatch(/pruneDismissals/);

        // Nothing about this is ever shown as an error: a message that cannot
        // be fetched simply does not appear. Worth knowing, because it means
        // "no message today" and "the server is unreachable" look identical to
        // everyone, including us.
        expect(notifications).toMatch(/catch/);
        expect(notifications).not.toMatch(/throw new Error/);
    });
});

describe('Netflix support and what the documents say about it', () => {
    /**
     * Behaviour map §36, and the map's wording needed correcting: the extension
     * does NOT run on Netflix "without saying so". The store listing names
     * Netflix in both its title and its description.
     *
     * The real gap is narrower and is in the privacy policy: it introduces
     * itself as covering two editions, HDrezka and YouTube, and describes the
     * saved-word source tag as "HDrezka or YouTube" — while the same extension
     * runs on Netflix and labels data `netflix`.
     *
     * A reader checking whether the policy covers the Netflix they were
     * promised on the storefront finds the platform named once, in a list of
     * label values, and nowhere in the description of what the product is.
     */
    test('the policy names Netflix where the storefront promises it', () => {
        const listing = JSON.parse(
            readFileSync(join(__dirname, '..', '_locales', 'en', 'messages.json'), 'utf8'),
        );
        const policy = readFileSync(join(__dirname, '..', '..', '..', 'PRIVACY_POLICY.md'), 'utf8');

        // The storefront is explicit.
        expect(listing.appName.message).toMatch(/Netflix/);
        expect(listing.appDesc.message).toMatch(/Netflix/);

        // So the policy must be too, where it introduces what it covers — not
        // only as one value in a list of platform labels.
        const editionsBlock = policy.slice(0, policy.indexOf('## TL;DR'));
        expect(editionsBlock).toMatch(/Netflix/i);

        // And in the source tag a saved word carries.
        expect(policy).toMatch(/`netflix`/);
    });

    test('Netflix runs inside this extension rather than an edition of its own', () => {
        // Which is why nobody installing "for YouTube" would think to look for a
        // separate listing — and why the policy naming two editions leaves the
        // third surface undescribed.
        const manifest = JSON.parse(readFileSync(join(__dirname, '..', 'manifest.json'), 'utf8'));
        const matches = JSON.stringify(manifest.content_scripts);
        expect(matches).toMatch(/netflix\.com/);
        expect(matches).toMatch(/youtube\.com/);
    });
});

/**
 * §34.3, T5.31 — the policy says the measurements cannot be deleted.
 *
 * Not a known gap: a stated fact about the product, and the one the analytics
 * design turns on. The events carry no account identifier, which is what makes
 * them anonymous — and the price of that is that nobody, the developer
 * included, can find a given person's events to remove them. A policy that
 * promised deletion here would be promising something the architecture cannot
 * do, which is the shape of a data-safety rejection.
 *
 * A document pin: red is obtained by editing PRIVACY_POLICY.md, not the code.
 */
describe('the policy states that measurements cannot be deleted', () => {
    const policy = (): string =>
        readFileSync(join(__dirname, '..', '..', '..', 'PRIVACY_POLICY.md'), 'utf8');

    test('it says the events cannot be looked up or deleted, by either party', () => {
        expect(policy()).toMatch(
            /we cannot look up or\s*\n?\s*delete the events belonging to a specific person — and neither can you/,
        );
    });

    test('it gives the reason: the events carry no account identifier', () => {
        expect(policy()).toMatch(/these events carry no account identifier/i);
    });

    // The other half of the same paragraph, and the part a user acts on: the
    // switch stops future collection but cannot reach back. Without this, the
    // sentence above could be read as "your data is stuck here forever".
    test('it says opting out stops collection without removing what was sent', () => {
        const text = policy();
        expect(text).toMatch(/stops any further collection/i);
        expect(text).toMatch(/cannot retroactively remove/i);
        expect(text).toMatch(/2-month/);
    });
});
